### ISSUE TITLE
migrate to dune

### ISSUE THREAD

**Issue by c-cube** [vincent-hugot/qtest#50]
This would be perfect to have: https://github.com/ocaml/dune/pull/338#issuecomment-367739619

**Comment by c-cube** [comment]
This works now. Next release should be on dune.

**Comment by c-cube** [comment]
this might be a problem for Batteries, since they might still support < 4.02. @gasche @UnixJunkie @murmour any opinion on that?

**Comment by gasche** [comment]
So yes, ideally I would like Batteries to support older releases than 4.02, but I don't think this should constrain downstream project choices. qtest is morally an optional dependency and we can manage to allow users to install with older OCaml versions (we were already doing some of that because of the use of GADTs in recent versions of qtest).

**Comment by c-cube** [comment]
Thank you, that's helpful. I should release soon then (with the integrated dune support, which makes it much easier for dune projects to use qtest).

**Comment by c-cube** [comment]
Thank you, that's helpful. I should release soon then (with the integrated dune support, which makes it much easier for dune projects to use qtest).
